[frontends.tcp_3000]
listen_addr = "192.168.1.136:3000"
backend = "tcp3000_out"

[frontends.tcp_3001]
listen_addr = "192.168.1.136:3001"
backend = "tcp3001_out"

[backends.tcp3000_out]
  health_check_interval = 3
  [backends.tcp3000_out.servers]
    [backends.tcp3000_out.servers.server1]
    addr = "192.168.1.128:80"
    weight = 10
    [backends.tcp3000_out.servers.server2]
    addr = "192.168.1.118:80"
    weight = 100
    [backends.tcp3000_out.servers.server3]
    addr = "192.168.1.138:8084"
    weight = 1
    [backends.tcp3000_out.servers.server4]
    addr = "192.168.1.184:8080"
    weight = 1

[backends.tcp3001_out]
  health_check_interval = 3
  [backends.tcp3001_out.servers]
    [backends.tcp3001_out.servers.server2]
    addr = "192.168.2.10:8083"
    weight = 1
    [backends.tcp3001_out.servers.server3]
    addr = "192.168.2.11:8082"

[stats]
port = "7000"
