[frontends.http_3000]
listen_addr = "0.0.0.0:3000"
backend = "tcp_out"

[frontends.http_3001]
listen_addr = "0.0.0.0:3001"
backend = "tcp2_out"

[backends.tcp_out]
  health_check_interval = 3
  [backends.tcp_out.servers]
    [backends.tcp_out.servers.server1]
    addr = "127.0.0.1:8080"
    weight = 1
    [backends.tcp_out.servers.server2]
    addr = "127.0.0.1:8081"
    weight = 1
    [backends.tcp_out.servers.server3]
    addr = "127.0.0.1:8082"
    [backends.tcp_out.servers.server4]
    addr = "127.0.0.1:8085"
    weight = 1000

[backends.tcp2_out]
  health_check_interval = 3
  [backends.tcp2_out.servers]
    [backends.tcp2_out.servers.server1]
    addr = "127.0.0.1:8080"
    weight = 2
    [backends.tcp2_out.servers.server2]
    addr = "127.0.0.1:8081"
    weight = 1
    [backends.tcp2_out.servers.server3]
    addr = "127.0.0.1:8082"

[stats]
port = "7000"
