[frontends.tcp_3000]
listen_addr = "192.168.1.136:3000"
backend = "tcp3000_out"

[backends.tcp3000_out]
  health_check_interval = 3
  [backends.tcp3000_out.servers]
    [backends.tcp3000_out.servers.server1]
    addr = "192.168.1.128:8080"
    weight = 10

[backends.tcp3001_out]
  health_check_interval = 3
  [backends.tcp3001_out.servers]
    [backends.tcp3001_out.servers.server2]
    addr = "127.0.0.3:8083"
    weight = 1
    [backends.tcp3001_out.servers.server3]
    addr = "127.0.0.3:8082"

[stats]
port = "7000"

[passthrough]
connection_tracker_capacity = 3
